export default [
    {
      id: 1,
      postedOn: "Fri Oct 21 2022 00:02:00 GMT+0700",
      title: "Frontend Developer",
      type: "Full time",
      location: "Remote",
      image:"",
      companyName: "Rikkeisoft",
      companyUrl: "rikkeisoft.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://tuyendung.rikkeisoft.com/",
    },
    {
      id: 2,
      postedOn: "Wed Oct 19 2022 22:49:20 GMT+0700",
      title: "Backend Developer",
      type: "Part time",
      location: "Office",
      companyName: "MGM Technology partners Vietnam",
      companyUrl: "Mgm.com",
      skills: ["Angular", "Node.js"],
      link: "https://jobs.mgm-tp.com/",
    },
    {
      id: 3,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Mobile dev",
      type: "Contract",
      location: "Remote",
      companyName: "Facebook",
      companyUrl: "https://enouvo.com",
      skills: ["flutter"],
      link: "https://enouvo.com/career/",
    },
  ];    