export default [
    {
      id: 1,
      postedOn: "Fri Oct 21 2022 00:02:00 GMT+0700",
      title: "Nguyen Son",
      type: "Full time",
      location: "Remote",
      image:"",
      companyName: "K25-CMU-TPM1",
      companyUrl: "rikkeisoft.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://tuyendung.rikkeisoft.com/",
    },
    {
      id: 2,
      postedOn: "Wed Oct 19 2022 22:49:20 GMT+0700",
      title: "Pham Ngoc Chan",
      type: "Part time",
      location: "Office",
      companyName: "K25-CMU-TTT",
      companyUrl: "Mgm.com",
      skills: ["Angular", "Node.js","Java"],
      link: "https://jobs.mgm-tp.com/",
    },
    {
      id: 3,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Nguyen Hoang",
      type: "Contract",
      location: "Remote",
      companyName: "K25-CMU-TPM2",
      companyUrl: "https://enouvo.com",
      skills: ["HTML", "CSS", "JavaScript"],
      link: "https://enouvo.com/career/",
    },
    {
      id: 4,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Nguyen Hung",
      type: "Contract",
      location: "Remote",
      companyName: "K24-CMU-TPM5",
      companyUrl: "https://enouvo.com",
      skills: ["Java", "C++"],
      link: "https://enouvo.com/career/",
    },
    {
      id: 5,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Dang Thien Kiet",
      type: "Contract",
      location: "Remote",
      companyName: "K25-CMU-TTT",
      companyUrl: "https://enouvo.com",
      skills: ["NodeJS","ReactJS"],
      link: "https://enouvo.com/career/",
    },
    {
      id: 6,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Dang Nam",
      type: "Contract",
      location: "Remote",
      companyName: "K25-CMU-TPM7",
      companyUrl: "https://enouvo.com",
      skills: ["HTML","CSS","Java"],
      link: "https://enouvo.com/career/",
    },
    {
      id: 7,
      postedOn: "Thu Oct 20 2022 22:49:20 GMT+0700",
      title: "Huynh Ba Hai",
      type: "Contract",
      location: "Remote",
      companyName: "K24-CMU-TPM6",
      companyUrl: "https://enouvo.com",
      skills: ["NodeJS", "JavaScript"],
      link: "https://enouvo.com/career/",
    },
  ];    